#!/usr/bin/env bash

function audit_subdomain {
    domain=$1
    subdomain=$2
    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi
    for subdomain in "${subdomains[@]}"; do
        record_type=$(dig +short -t CNAME "$subdomain"."$domain" | awk '{print $1}')
        destination=$(dig +short "$subdomain"."$domain" | awk '{print $1}')
        echo "The subdomain $subdomain is a $record_type record and points to $destination"
    done
}

audit_subdomain "$1" "$2"
