#!/usr/bin/env bash
# A script that configures nginx and redirect a url

sudo apt-get update
sudo apt-get install -y nginx

#setting up a redirection for '/redirect_me' and set custom headers
replacement_string="server_name_;\n\tadd_header X-Served-By $hostname;"
sudo sed -i "s/server_name_;/$replacement_string/" /etc/nginx/sites-enabled/default

sudo service nginx restart
