#!/usr/bin/env bash
# A script that install and configure haproxy
# on a new ubuntu with a frontend and backend config
# for two servers with a roundrobin algorithm

sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend grade-frontend
        bind *:80
        mode http
        default_backend grade-backend
backend grade-backend
        balance roundrobin
        server 129952-web-01 52.91.131.225:80 check
        server 129952-web-02 3.85.148.88:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
