#!/usr/bin/env bash

# Write a Bash script that displays the time for 12 hours and 59 minutes:

# display hours from 0 to 12
# display minutes from 1 to 59

hour=0

while [ $hour -lt 13 ]; do
	echo "Hour: $hour"
	i=1
	while [ $i -le 59 ]; do
		echo "$i"
		i=$((i+1))
	done
	hour=$((hour+1))
done
